# OPTIONAL configuration file for romaudit_cli v2.0.0
# 
# This file is NOT REQUIRED - the tool works perfectly with default settings.
# Only create this file if you need to customize the default behavior.
#
# To use: Save as 'config.toml' in the same directory as romaudit_cli
# To enable: Uncomment the 'toml' dependency in Cargo.toml and rebuild
#
# NOTE: romaudit_cli only works with uncompressed ROM files.
# Extract all ROMs from ZIP/7Z/RAR archives before scanning.
#
# v2.0.0 complete modular architecture refactoring (100% compatible)
# v1.6.4 adds MAME DAT type detection for space-efficient organization.
# v1.6.3 fixes critical bug where incomplete folders were created for absent games.
# All games now follow the same folder rules.

# Directory configuration
rom_dir = "roms"
logs_dir = "logs"
db_file = "rom_db.json"
duplicate_prefix = "duplicates"
unknown_prefix = "unknown"

# Performance tuning
buffer_size = 1048576  # 1MB in bytes

# Words to ignore when comparing ROM names
stop_words = [
    "the", "of", "and", "a", "an",
    "in", "on", "at", "to", "for"
]

# Note: The tool automatically detects and uses the first .dat or .xml file
# found in the current directory. No configuration needed for DAT/XML files.